<?php

namespace Backend\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClassifiedAdvertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifiedAdvertisementRepository extends EntityRepository
{
}
