# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  resource.user:
    parent:    "api.resource"
    arguments: [ "Backend\\AdminBundle\\Entity\\User" ]
    calls:
      -      method:    "initNormalizationContext"
             arguments: [ { groups: [ "user" ] } ]
      -      method:    "initDenormalizationContext"
             arguments: [ { groups: [ "user" ] } ]
    tags:      [ { name: "api.resource" } ]
  resource.classifiedadvertisement:
    parent:    "api.resource"
    arguments: [ "Backend\\AdminBundle\\Entity\\ClassifiedAdvertisement" ]
    tags:      [ { name: "api.resource" } ]
  resource.media:
    parent:    "api.resource"
    arguments: [ "Backend\\AdminBundle\\Entity\\Media" ]
    tags:      [ { name: "api.resource" } ]
  resource.category:
    parent:    "api.resource"
    arguments: [ "Backend\\AdminBundle\\Entity\\Category" ]
    tags:      [ { name: "api.resource" } ]